#!/bin/bash

#SBATCH --job-name=fd_lm_big
#SBATCH --time=20:00:00
#SBATCH --partition=gpu_shared
#SBATCH --gres=gpu:1
#SBATCH --mem=60G

module load 2019
module load CUDA/10.0.130
module load cuDNN/7.6.3-CUDA-10.0.130

source ~/anaconda3/etc/profile.d/conda.sh
conda init
conda activate indist

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/sw/arch/Debian9/EB_production/2019/software/CUDA/10.0.130/extras/CUPTI/lib64/


HEAD_DIR="/home/samigpu/Codes/InDist"
CODE_DIR=$HEAD_DIR/
DATA_DIR=$HEAD_DIR/data
LOGS_DIR=$HEAD_DIR/logs

export PYTHONPATH=$PYTHONPATH:$HEAD_DIR

# 100, 101, 102 small lisa_crs_slw_offlineteacher_v10
# 116, 117, 118 big lisa_crs_slw_offlineteacher_v10

# 400, 401, 402 big  0.001_lisa_crs_fst_offlineteacher_v20
# 405, 406, 407 small  0.001_lisa_crs_fst_offlineteacher_v20

# 500, 501, 502 small  0.001_lisa_crs_fst_offlineteacher_v22
# 505, 506, 507 big  0.001_lisa_crs_fst_offlineteacher_v22


CUDA_VISIBLE_DEVICES=0 python $CODE_DIR/distill/distill_main.py --task=word_sv_agreement_lm \
--teacher_model=lm_lstm_shared_emb \
--teacher_exp_name=0.001_lisa_crs_fst_offlineteacher_v22 \
--student_model=lm_gpt2 \
--student_exp_name=lisa_fd502 \
--teacher_config=biglstm_drop31_v2 \
--student_config=big_gpt_v5 \
--distill_mode=offline \
--distill_config=dstl_6_crs_slw
