#!/bin/bash

#SBATCH --job-name=fd_lm
#SBATCH --time=20:00:00
#SBATCH --partition=gpu_shared
#SBATCH --gres=gpu:1
#SBATCH --mem=60G

module load 2019
module load CUDA/10.0.130
module load cuDNN/7.6.3-CUDA-10.0.130

source ~/anaconda3/etc/profile.d/conda.sh
conda init
conda activate indist

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/sw/arch/Debian9/EB_production/2019/software/CUDA/10.0.130/extras/CUPTI/lib64/


HEAD_DIR="/home/samigpu/Codes/InDist"
CODE_DIR=$HEAD_DIR/
DATA_DIR=$HEAD_DIR/data
LOGS_DIR=$HEAD_DIR/logs

export PYTHONPATH=$PYTHONPATH:$HEAD_DIR

# 0.001_lisa_crs_slw_offlineteacher_v10
# 105, 106, 107
# 111, 112, 113
# 0.001_lisa_offlineteacher_v3
# 210 211 212
# 215, 216, 217

# 0.001_lisa_crs_fst_offlineteacher_v20
# 430 431 432 big
# 435 436 437 small

CUDA_VISIBLE_DEVICES=0 python $CODE_DIR/distill/distill_main.py --task=word_sv_agreement_lm \
--teacher_exp_name=0.001_lisa_crs_fst_offlineteacher_v20 \
--student_exp_name=lisa_fd432 \
--teacher_model=lm_lstm_shared_emb \
--student_model=lm_gpt2 \
--teacher_config=lstm_drop31_v2 \
--student_config=very_big_gpt_v10 \
--distill_mode=offline \
--distill_config=dstl_6_crs_slw
