#!/bin/bash

#SBATCH --job-name=rep_sst
#SBATCH --time=10:00:00
#SBATCH --partition=gpu

module load 2019
module load CUDA/10.1.243
module load cuDNN/7.6.5.32-CUDA-10.1.243

source ~/anaconda3/etc/profile.d/conda.sh
conda init
conda activate indist

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243/extras/CUPTI/lib64/

HEAD_DIR="/home/samigpu/Codes/InDist"
CODE_DIR=$HEAD_DIR/
DATA_DIR=$HEAD_DIR/data
LOGS_DIR=$HEAD_DIR/logs

export PYTHONPATH=$PYTHONPATH:$HEAD_DIR


CUDA_VISIBLE_DEVICES=0 python $CODE_DIR/distill/repshare_main.py --task=sst2 \
--teacher_model=cl_lstm \
--student_model=cl_lstm \
--teacher_exp_name=lisa_or_tchr1 \
--student_exp_name=lisa_std1 \
--teacher_config=small_lstm_v4 \
--student_config=small_lstm_v4 \
--batch_size=128 \
--distill_mode=rep_online \
--distill_config=rpdst_019_crs_slwfst_2 &


CUDA_VISIBLE_DEVICES=1 python $CODE_DIR/distill/repshare_main.py --task=sst2 \
--teacher_model=cl_lstm \
--student_model=cl_lstm \
--teacher_exp_name=lisa_or_tchr2 \
--student_exp_name=lisa_std2 \
--teacher_config=small_lstm_v4 \
--student_config=small_lstm_v4 \
--distill_mode=rep_online \
--batch_size=128 \
--distill_config=rpdst_019_crs_slwfst_3 &

CUDA_VISIBLE_DEVICES=2 python $CODE_DIR/distill/repshare_main.py --task=sst2 \
--teacher_model=cl_lstm \
--student_model=cl_lstm \
--teacher_exp_name=lisa_or_tchr3 \
--student_exp_name=lisa_std3 \
--teacher_config=small_lstm_v4 \
--student_config=small_lstm_v4 \
--distill_mode=rep_online \
--batch_size=128 \
--distill_config=rpdst_0010_crs_slwfst_2 &


CUDA_VISIBLE_DEVICES=3 python $CODE_DIR/distill/repshare_main.py --task=sst2 \
--teacher_model=cl_lstm \
--student_model=cl_lstm \
--teacher_exp_name=lisa_or_tchr4 \
--student_exp_name=lisa_std4 \
--teacher_config=small_lstm_v4 \
--student_config=small_lstm_v4 \
--distill_mode=rep_online \
--batch_size=128 \
--distill_config=rpdst_0010_crs_slwfst_3 &

wait
