#!/bin/bash

#SBATCH --job-name=orep_lm
#SBATCH --time=24:00:00
#SBATCH --partition=gpu_shared

module load 2019
module load CUDA/10.1.243
module load cuDNN/7.6.5.32-CUDA-10.1.243

source ~/anaconda3/etc/profile.d/conda.sh
conda init
conda activate indist

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243/extras/CUPTI/lib64/

HEAD_DIR="/home/samigpu/Codes/InDist"
CODE_DIR=$HEAD_DIR/
DATA_DIR=$HEAD_DIR/data
LOGS_DIR=$HEAD_DIR/logs

export PYTHONPATH=$PYTHONPATH:$HEAD_DIR


python $CODE_DIR/distill/repshare_main.py --task=word_sv_agreement_lm \
--teacher_model=lm_lstm_shared_emb \
--student_model=lm_lstm_shared_emb \
--student_exp_name=lisa_std2 \
--teacher_exp_name=lisa_or_tchr2 \
--teacher_config=biglstm_drop31_v2 \
--student_config=biglstm_drop31_v2 \
--distill_mode=rep_online \
--distill_config=rpdst_019_crs_slwfst_2 &

python $CODE_DIR/distill/repshare_main.py --task=word_sv_agreement_lm \
--teacher_model=lm_lstm_shared_emb \
--student_model=lm_lstm_shared_emb \
--student_exp_name=lisa_std10 \
--teacher_exp_name=lisa_or_tchr10 \
--teacher_config=biglstm_drop31_v2 \
--student_config=biglstm_drop31_v2 \
--distill_mode=rep_online \
--distill_config=rpdst_019_crs_slwfst_3 &

CUDA_VISIBLE_DEVICES=2 python $CODE_DIR/distill/repshare_main.py --task=word_sv_agreement_lm \
--teacher_model=lm_lstm_shared_emb \
--student_model=lm_lstm_shared_emb \
--student_exp_name=lisa_std20 \
--teacher_exp_name=lisa_or_tchr20 \
--teacher_config=biglstm_drop31_v2 \
--student_config=biglstm_drop31_v2 \
--distill_mode=rep_online \
--distill_config=rpdst_0010_crs_slwfst_2 &

CUDA_VISIBLE_DEVICES=2 python $CODE_DIR/distill/repshare_main.py --task=word_sv_agreement_lm \
--teacher_model=lm_lstm_shared_emb \
--student_model=lm_lstm_shared_emb \
--student_exp_name=lisa_std30 \
--teacher_exp_name=lisa_or_tchr30 \
--teacher_config=biglstm_drop31_v2 \
--student_config=biglstm_drop31_v2 \
--distill_mode=rep_online \
--distill_config=rpdst_0010_crs_slwfst_3 &

wait
