#!/bin/bash

#SBATCH --job-name=online_distill_lm
#SBATCH --time=20:00:00
#SBATCH --partition=gpu_shared
#SBATCH --gres=gpu:1
#SBATCH --mem=60G

module load 2019
module load CUDA/10.0.130
module load cuDNN/7.6.3-CUDA-10.0.130

source ~/anaconda3/etc/profile.d/conda.sh
conda init
conda activate indist

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/sw/arch/Debian9/EB_production/2019/software/CUDA/10.0.130/extras/CUPTI/lib64/

HEAD_DIR="/home/samigpu/Codes/InDist"
CODE_DIR=$HEAD_DIR/
DATA_DIR=$HEAD_DIR/data
LOGS_DIR=$HEAD_DIR/logs

export PYTHONPATH=$PYTHONPATH:$HEAD_DIR


CUDA_VISIBLE_DEVICES=0 python $CODE_DIR/distill/distill_main.py --task=sst2 \
--teacher_model=cl_lstm \
--student_model=cl_lstm \
--teacher_exp_name=lisa_rep_tchr1 \
--student_exp_name=lisa_rep_std1 \
--teacher_config=small_lstm_v4 \
--student_config=small_lstm_v4 \
--distill_mode=rep_online \
--distill_config=rpdst_019_crs_slwfst_2
