#!/bin/bash

#SBATCH --job-name=lm1b
#SBATCH --time=20:00:00
#SBATCH --partition=gpu_shared
#SBATCH --gres=gpu:1


module load 2019
module load CUDA/10.1.243
module load cuDNN/7.6.5.32-CUDA-10.1.243

source ~/anaconda3/etc/profile.d/conda.sh
conda init
conda activate indist

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/sw/arch/Debian10/EB_production/2019/software/CUDA/10.1.243/extras/CUPTI/lib64/

HEAD_DIR="/home/samigpu/Codes/InDist"
CODE_DIR=$HEAD_DIR/
DATA_DIR=$HEAD_DIR/data
LOGS_DIR=$HEAD_DIR/logs

export PYTHONPATH=$PYTHONPATH:$HEAD_DIR

CUDA_VISIBLE_DEVICES=0 python $CODE_DIR/keras_trainer.py \
--model=lm_lstm_shared_emb \
--task=lm1b \
--model_config=biglstm_drop31_v2 \
--train_config=crs_slw \
--exp_name=lisa_crs_slw_offlineteacher_v1