#!/bin/bash

#SBATCH --job-name=vp_lstm
#SBATCH --time=10:00:00
#SBATCH --partition=gpu

module load 2019
module load CUDA/10.0.130
module load cuDNN/7.6.3-CUDA-10.0.130

source ~/anaconda3/etc/profile.d/conda.sh
conda init
conda activate indist

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/sw/arch/Debian9/EB_production/2019/software/CUDA/10.0.130/extras/CUPTI/lib64/

HEAD_DIR="/home/samigpu/Codes/InDist"
CODE_DIR=$HEAD_DIR/
DATA_DIR=$HEAD_DIR/data
LOGS_DIR=$HEAD_DIR/logs

export PYTHONPATH=$PYTHONPATH:$HEAD_DIR

CUDA_VISIBLE_DEVICES=0 python $CODE_DIR/keras_trainer.py \
--model=cl_lstm \
--task=word_sv_agreement_vp \
--model_config=small_lstm_v4 \
--train_config=crs_slw \
--keep_checkpoint_every_n_hours=1 \
--exp_name=lisa_crs_slw_offlineteacher_v20 &

CUDA_VISIBLE_DEVICES=1 python $CODE_DIR/keras_trainer.py \
--model=cl_lstm \
--task=word_sv_agreement_vp \
--model_config=small_lstm_v4 \
--train_config=crs_slw \
--keep_checkpoint_every_n_hours=1 \
--exp_name=lisa_crs_slw_offlineteacher_v21 &

CUDA_VISIBLE_DEVICES=2 python $CODE_DIR/keras_trainer.py \
--model=cl_lstm \
--task=word_sv_agreement_vp \
--model_config=small_lstm_v4 \
--train_config=crs_slw \
--exp_name=lisa_crs_slw_offlineteacher_v22 &

CUDA_VISIBLE_DEVICES=3 python $CODE_DIR/keras_trainer.py \
--model=cl_lstm \
--task=word_sv_agreement_vp \
--model_config=small_lstm_v4 \
--train_config=crs_fst \
--exp_name=lisa_crs_fst_offlineteacher_v30 &

wait
